version: '3'

services:
  deloop:
    image: deloop/deloop:0.1.1
    container_name: deloop
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 9601:9601
    volumes:
      - deloop_data:/deloop/data


  deloop_web:
    image: deloop/deloop-web:0.1.1
    container_name: deloop-web
    restart: always
    build:
      context: .
      dockerfile: web.Dockerfile

  labelstudio:
    image: heartexlabs/label-studio:latest
    container_name: labelstudio
    restart: always
    environment:
      - LABEL_STUDIO_DISABLE_SIGNUP_WITHOUT_LINK=true
      - LABEL_STUDIO_USERNAME=admin@foo.com
      - LABEL_STUDIO_PASSWORD=foo123
      - CSRF_COOKIE_HTTPONLY=0
      - SESSION_COOKIE_SECURE=0
      - SESSION_COOKIE_HTTPONLY=0
    ports:
      - 8080:8080

  nginx:
    image: nginx:latest
    container_name: "nginx_proxy"
    restart: always
    expose:
      - 8000
    ports:
      - 8000:8000

    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.5.3
    container_name: elasticsearch
    restart: always
    environment:
      - node.name=elasticsearch
      - cluster.name=es-deloop-local
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
    ports:
      - 9200:9200
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticdata:/usr/share/elasticsearch/data

  minio:
    image: minio/minio:RELEASE.2024-01-13T07-53-03Z
    container_name: "minio"
    restart: always
    environment:
      - MINIO_ROOT_USER=ROOTNAME
      - MINIO_ROOT_PASSWORD=CHANGEME123
    command: server /data --console-address ":9001"
    ports:
      - 9001:9001
      - 9000:9000
    volumes:
      - miniodata:/data

volumes:
  elasticdata:
  miniodata:
  deloop_data:
